<a href="https://colab.research.google.com/github/j019/Practical-Machine-Learning/blob/main/Day14/Spacy_Wordnet_for_NLP_data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/Airline_sentiment.csv")

In [3]:
df.shape

(14640, 15)

In [4]:
df.columns

Index(['tweet_id', 'airline_sentiment', 'airline_sentiment_confidence',
       'negativereason', 'negativereason_confidence', 'airline',
       'airline_sentiment_gold', 'name', 'negativereason_gold',
       'retweet_count', 'text', 'tweet_coord', 'tweet_created',
       'tweet_location', 'user_timezone'],
      dtype='object')

In [5]:
df['text'].head()

0                  @VirginAmerica What @dhepburn said.
1    @VirginAmerica plus you've added commercials t...
2    @VirginAmerica I didn't today... Must mean I n...
3    @VirginAmerica it's really aggressive to blast...
4    @VirginAmerica and it's a really big bad thing...
Name: text, dtype: object

In [6]:
df['airline_sentiment'].head()

0     neutral
1    positive
2     neutral
3    negative
4    negative
Name: airline_sentiment, dtype: object

In [7]:
df['airline_sentiment'].unique()

array(['neutral', 'positive', 'negative'], dtype=object)

- It will do all preprocessing steps on text data --> spacy

In [8]:
import spacy
nlp = spacy.load('en_core_web_sm')
# update the stop word list to contain
# most frequent and
# most rare words from the dataset
# then apply the model to text
# ref : https://stackoverflow.com/questions/41170726/add-remove-custom-stop-words-with-spacy

In [9]:
all_text = df['text'].apply(nlp)

In [10]:
len(all_text)

14640

- use tokeniztion algorithm

In [11]:
all_text[:5]

0           (@VirginAmerica, What, @dhepburn, said, .)
1    (@VirginAmerica, plus, you, 've, added, commer...
2    (@VirginAmerica, I, did, n't, today, ..., Must...
3    (@VirginAmerica, it, 's, really, aggressive, t...
4    (@VirginAmerica, and, it, 's, a, really, big, ...
Name: text, dtype: object

In [15]:
# is_stop to remove stop words
# lemma_ to extract the lemmatized text
# like_num
# like_email
clean_text = []
for line in all_text:
  clean_line = []
  for token in line:
    if token.is_stop == True: # check for stop words
      pass
    elif token.like_num == True: # check for numeric value
      clean_line.append('num')
    elif token.like_email == True:
      clean_line.append('emailaddr')
    elif token.like_url == True:
      clean_line.append('url')
    elif token.__len__() <=2:
      pass
    elif (token.is_punct == True) or (token.is_quote == True):
      pass
    else:
     # NER
     #if token.ent_type_ == 'PERSON':
     # print(token)
      clean_line.append(token.lemma_.lower())

  clean_text.append(clean_line)

In [16]:
len(clean_text)

14640

In [17]:
clean_text[:5]

[['@virginamerica', '@dhepburn', 'say'],
 ['@virginamerica', 'plus', 'add', 'commercial', 'experience', 'tacky'],
 ['@virginamerica', 'today', 'mean', 'need', 'trip'],
 ['@virginamerica',
  'aggressive',
  'blast',
  'obnoxious',
  'entertainment',
  'guest',
  'face',
  'amp',
  'little',
  'recourse'],
 ['@virginamerica', 'big', 'bad', 'thing']]

# Create dictionary of unique words

In [18]:
clean_text_list = sum(clean_text,[])

# program, plan  --> replace second one with the first one

In [19]:
len(clean_text_list), clean_text_list[:5]

(131217, ['@virginamerica', '@dhepburn', 'say', '@virginamerica', 'plus'])

In [20]:
dictionary = set(clean_text_list)

In [21]:
len(dictionary)

11390

In [22]:
list(dictionary)[:5]

['@_austrian', 'female', 'justgetmehome', 'schoolgirl', 'tonight!great']

# Extra

## Use wordnet to check Synonyms

- wordnet (library) --> words and synonyms or synsets(includes synonyms and antonyms)

## Sample program for checking synonyms and antonyms

In [23]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [24]:
from nltk.corpus import wordnet

In [25]:
syns = wordnet.synsets("program")

In [26]:
syns

[Synset('plan.n.01'),
 Synset('program.n.02'),
 Synset('broadcast.n.02'),
 Synset('platform.n.02'),
 Synset('program.n.05'),
 Synset('course_of_study.n.01'),
 Synset('program.n.07'),
 Synset('program.n.08'),
 Synset('program.v.01'),
 Synset('program.v.02')]

In [27]:
for i in range(len(syns)):
   print(syns[i].lemmas()[0].name())

plan
program
broadcast
platform
program
course_of_study
program
program
program
program

In [28]:
synonyms = []
antonyms = []

for syn in wordnet.synsets("good"):
    for l in syn.lemmas():
        synonyms.append(l.name())
        if l.antonyms():
            antonyms.append(l.antonyms()[0].name())

print(set(synonyms))
print(set(antonyms))

{'honorable', 'ripe', 'right', 'sound', 'estimable', 'dependable', 'dear', 'respectable', 'safe', 'in_effect', 'goodness', 'unspoilt', 'serious', 'just', 'secure', 'proficient', 'skilful', 'commodity', 'beneficial', 'near', 'adept', 'effective', 'salutary', 'full', 'thoroughly', 'skillful', 'undecomposed', 'trade_good', 'practiced', 'good', 'upright', 'soundly', 'in_force', 'expert', 'well', 'unspoiled', 'honest'}
{'ill', 'bad', 'badness', 'evilness', 'evil'}

#### Reference : https://pythonprogramming.net/wordnet-nltk-tutorial/

## Apply wordnet for reducing features in dictionary

In [29]:
word_map={}
rev_map={}
for word in dictionary:
  if word not in rev_map:
    word_map[word]=[]
    for syn in wordnet.synsets(word):
      for l in syn.lemmas():
        if (l.name() != word) and (l.name() in dictionary):
          word_map[word].append(l.name())
          rev_map[l.name()]=word

In [30]:
len(word_map)

9564

In [31]:
len(rev_map)

2099

In [32]:
rev_map

{'outstanding': 'greatest',
 'junk': 'dust',
 'scatter': 'dust',
 'sprinkle': 'dust',
 'dot': 'points',
 'draw': 'forced',
 'catch': 'grab',
 'cart': 'haul',
 'drag': 'haul',
 'mile': 'miles',
 'crook': 'criminal',
 'twist': 'device',
 'play': 'working',
 'go': 'adam',
 'spell': 'piece',
 'tour': 'circuit',
 'bout': 'turn',
 'round': 'beats',
 'act': 'working',
 'routine': 'mundane',
 'number': 'numbered',
 'bit': 'piece',
 'reverse': 'turnaround',
 'grow': 'farms',
 'release': 'waiver',
 'plow': 'deals',
 'plough': 'turn',
 'wrench': 'turn',
 'rick': 'turn',
 'flex': 'turn',
 'sour': 'working',
 'work': 'working',
 'regard': 'respect',
 'assuage': 'relieved',
 'appease': 'pacify',
 'action': 'processing',
 'process': 'working',
 'gang': 'ring',
 'crowd': 'herded',
 'bunch': 'cluster',
 'hope': 'promise',
 'assure': 'assuring',
 'predict': 'calls',
 'call': 'calls',
 'anticipate': 'calls',
 'repair': 'revive',
 'fix': 'makes',
 'doctor': 'dr.',
 'reinstate': 'restore',
 'chicken': 'yellow',
 'issue': 'issues',
 'take': 'assumed',
 'yield': 'afford',
 'counter': 'return',
 'revert': 'return',
 'repay': 'rewards',
 'refund': 'refunded',
 'deliver': 'having',
 'fall': 'hung',
 'pass': 'heads',
 'give': 'fed',
 'generate': 'got',
 'plan': 'programs',
 'fate': 'lots',
 'designate': 'points',
 'crap': 'makes',
 'dirt': 'scandal',
 'poop': 'quarter',
 'bullshit': 'shit',
 'bull': 'cop',
 'jack': 'jackass',
 'dump': 'dumps',
 'asshole': 'sob',
 'bastard': 'sob',
 'dickhead': 'sob',
 'damn': 'blame',
 'darn': 'shit',
 'hoot': 'bird',
 'rat': 'rats',
 'shop': 'rats',
 'make': 'working',
 'necessity': 'necessary',
 'essential': 'crucial',
 'requirement': 'demand',
 'network': 'webs',
 'net': 'webs',
 'pad': 'tablet',
 'marshal': 'marshall',
 'minimum': 'minimal',
 'favorite': 'pet',
 'preferred': 'pet',
 'dream': 'daydream',
 'moon': 'daydream',
 'blah': 'rant',
 'rave': 'rant',
 'dog': 'tracking',
 'snap': 'grab',
 'tick': 'checked',
 'dawn': 'morning',
 'laugh': 'laughing',
 'prank': 'joke',
 'trick': 'joke',
 'achieve': 'attain',
 'accomplish': 'attain',
 'reach': 'passed',
 'hit': 'makes',
 'strike': 'assumed',
 'discover': 'breaks',
 'gain': 'makes',
 'charge': 'cares',
 'rush': 'hurry',
 'thrill': 'inebriate',
 'kick': 'complain',
 'reboot': 'boot',
 'amaze': 'beating',
 'astound': 'amazing',
 'rap': 'belt',
 'fault': 'breaks',
 'pick': 'piece',
 'goddamn': 'blame',
 'curious': 'peculiar',
 'funny': 'shady',
 'odd': 'left',
 'rum': 'peculiar',
 'particular': 'specific',
 'special': 'exceptional',
 'try': 'testing',
 'seek': 'searching',
 'attempt': 'tried',
 'test': 'screens',
 'prove': 'testing',
 'sample': 'tried',
 'taste': 'preference',
 'hear': 'listening',
 'stress': 'emphasize',
 'truly': 'genuinely',
 'entertain': 'holding',
 'harbor': 'holding',
 'hold': 'reserved',
 'state': 'states',
 'say': 'states',
 'tell': 'states',
 'suppose': 'thought',
 'read': 'took',
 'order': 'clubs',
 'pronounce': 'says',
 'aforementioned': 'said',
 'attire': 'dress',
 'clothe': 'clothing',
 'arrange': 'format',
 'set': 'dos',
 'rage': 'madness',
 'storm': 'forced',
 'boss': 'chief',
 'stamp': 'embossed',
 'complete': 'pure',
 'murder': 'hits',
 'remove': 'took',
 'ticket': 'ticketing',
 'okay': 'approve',
 'alright': 'fine',
 'pat': 'tap',
 'tip': 'points',
 'bug': 'germ',
 'knock': 'bumping',
 'pink': 'ping',
 'beg': 'pray',
 'pity': 'compassion',
 'line': 'business',
 'wire': 'wires',
 'use': 'role',
 'exercise': 'working',
 'custom': 'customs',
 'get': 'took',
 'acquire': 'assumed',
 'let': 'having',
 'have': 'took',
 'receive': 'welcome',
 'find': 'bumping',
 'obtain': 'holding',
 'incur': 'got',
 'arrive': 'arriving',
 'come': 'numbered',
 'bring': 'working',
 'convey': 'took',
 'experience': 'having',
 'induce': 'having',
 'cause': 'lawsuit',
 'capture': 'got',
 'develop': 'breaks',
 'produce': 'makes',
 'contract': 'took',
 'drive': 'took',
 'aim': 'took',
 'stick': 'lodging',
 'beat': 'beating',
 'begin': 'got',
 'start': 'departing',
 'commence': 'got',
 'suffer': 'having',
 'father': 'got',
 'mother': 'got',
 'undermine': 'sabotage',
 'guidance': 'steering',
 'direction': 'management',
 'steer': 'heads',
 'maneuver': 'heads',
 'direct': 'took',
 'point': 'charging',
 'head': 'heads',
 'guide': 'took',
 'zip': 'zipper',
 'push': 'forced',
 'stone': 'rocks',
 'sway': 'rocks',
 'shake': 'rocks',
 'vino': 'wine',
 'awful': 'nasty',
 'dreadful': 'frightening',
 'painful': 'atrocious',
 'terrible': 'severe',
 'horrible': 'atrocious',
 'buck': 'charging',
 'relax': 'unwind',
 'alternative': 'alternatives',
 'choice': 'alternatives',
 'selection': 'option',
 'gone': 'asleep',
 'company': 'society',
 'worthy': 'desirable',
 'cutting': 'slip',
 'trip': 'tripping',
 'strip': 'peel',
 'shift': 'breaks',
 'case': 'lawsuit',
 'steal': 'stole',
 'slew': 'deals',
 'slide': 'coast',
 'err': 'mistaken',
 'mistake': 'mistaken',
 'birth': 'having',
 'stand': 'stood',
 'support': 'confirmed',
 'accept': 'assumed',
 'assume': 'assumed',
 'carry': 'took',
 'contain': 'took',
 'pay': 'compensate',
 'wear': 'assumed',
 'behave': 'dos',
 'expect': 'waiting',
 'high': 'higher',
 'size': 'sizer',
 'scene': 'views',
 'shaft': 'ray',
 'slam': 'shot',
 'dig': 'labor',
 'guess': 'estimated',
 'shoot': 'charging',
 'blast': 'blasting',
 'film': 'took',
 'dart': 'flutter',
 'scoot': 'shot',
 'tear': 'charging',
 'fool': 'marks',
 'bid': 'calls',
 'takeoff': 'parody',
 'festivity': 'celebration',
 'transit': 'transportation',
 'transport': 'delighted',
 'transfer': 'changing',
 'fare': 'dos',
 'superb': 'brilliant',
 'bright': 'smart',
 'decide': 'resolved',
 'resolve': 'resolved',
 'determine': 'checked',
 'locate': 'settle',
 'sink': 'cesspool',
 'finalize': 'settle',
 'descend': 'condescend',
 'accessibility': 'availability',
 'exit': 'exiting',
 'allow': 'reserved',
 'provide': 'catering',
 'result': 'issues',
 'lead': 'took',
 'depart': 'departing',
 'entrust': 'committed',
 'will': 'willing',
 'forget': 'forgot',
 'outbound': 'outward',
 'gather': 'tuck',
 'cod': 'bait',
 'force': 'forced',
 'decent': 'properly',
 'skillful': 'nicest',
 'courteous': 'nicest',
 'gracious': 'nicest',
 'put': 'committed',
 'commit': 'charging',
 'place': 'points',
 'gift': 'talent',
 'seat': 'bums',
 'flip': 'skys',
 'toss': 'skys',
 'club': 'clubs',
 'digit': 'fingers',
 'feel': 'feels',
 'center': 'mall',
 'middle': 'eyes',
 'midway': 'halfway',
 'astounded': 'amazed',
 'contempt': 'despite',
 'smiling': 'smile',
 'replacement': 'alternate',
 'jump': 'springs',
 'switch': 'trading',
 'substitute': 'replace',
 'deplorable': 'criminal',
 'miserable': 'poorest',
 'wretched': 'poorest',
 'tag': 'tracking',
 'label': 'marks',
 'mark': 'scared',
 'chase': 'tracking',
 'tail': 'bums',
 'track': 'crossed',
 'shiver': 'chill',
 'cool': 'chill',
 'heavy': 'overweight',
 'hard': 'difficult',
 'medal': 'medallion',
 'palm': 'medallion',
 'person': 'somebody',
 'individual': 'private',
 'someone': 'somebody',
 'soul': 'somebody',
 'runway': 'rail',
 'train': 'took',
 'infant': 'baby',
 'child': 'children',
 'sister': 'sis',
 'pamper': 'baby',
 'spoil': 'crossed',
 'link': 'connected',
 'bind': 'holding',
 'connect': 'connected',
 'attach': 'tie',
 'marry': 'weds',
 'grandmother': 'grandma',
 'granny': 'grandma',
 'stop': 'bars',
 'discontinue': 'breaks',
 'cease': 'stopped',
 'quit': 'departing',
 'block': 'bars',
 'break': 'bumping',
 'check': 'delays',
 'end': 'stopped',
 'finish': 'culture',
 'bar': 'bars',
 'open': 'afford',
 'unresolved': 'undetermined',
 'cud': 'plug',
 'hack': 'taxis',
 'secure': 'assuring',
 'part': 'role',
 'share': 'percentage',
 'donation': 'contribution',
 'jeopardy': 'hazard',
 'risk': 'danger',
 'luck': 'lots',
 'chance': 'bumping',
 'venture': 'hazard',
 'pretend': 'makes',
 'adventure': 'hazard',
 'filter': 'trickle',
 'randomly': 'arbitrarily',
 'chain': 'strand',
 'string': 'thread',
 'ground': 'stranded',
 'review': 'recap',
 'incredible': 'unbelievable',
 'unlikely': 'unbelievable',
 'strategy': 'scheme',
 'system': 'organization',
 'outline': 'draft',
 'sorry': 'worse',
 'belong': 'went',
 'vacate': 'abandon',
 'empty': 'evacuate',
 'desert': 'abandon',
 'pearl': 'bone',
 'unload': 'dropping',
 'spend': 'dropping',
 'swing': 'dropping',
 'dismiss': 'dropping',
 'throw': 'having',
 'neglect': 'dropping',
 'miss': 'dropping',
 'overlook': 'dropping',
 'deteriorate': 'dropping',
 'swindle': 'scam',
 'con': 'memorize',
 'rectify': 'reclaim',
 'amend': 'improve',
 'truthful': 'true',
 'dependable': 'best',
 'honest': 'best',
 'reliable': 'true',
 'genuine': 'true',
 'straight': 'consecutive',
 'clear': 'passed',
 'earn': 'makes',
 'realize': 'understood',
 'realise': 'understood',
 'goal': 'destination',
 'address': 'calls',
 'market': 'marketing',
 'advise': 'notify',
 'fulfill': 'satisfied',
 'fulfil': 'satisfied',
 'meet': 'satisfied',
 'fill': 'took',
 'air': 'aires',
 'shade': 'spook',
 'lag': 'interim',
 'jail': 'lagging',
 'sign': 'bless',
 'die': 'breaks',
 'spring': 'springs',
 'outlook': 'mindset',
 'anticipation': 'expectation',
 'report': 'reputation',
 'account': 'history',
 'trace': 'hunting',
 'key': 'paint',
 'distinguish': 'telling',
 'name': 'list',
 'hoop': 'basket',
 'pack': 'james',
 'band': 'lots',
 'telephone': 'calls',
 'phone': 'calls',
 'surround': 'environment',
 'border': 'march',
 'enter': 'recording',
 'enrol': 'enroll',
 'recruit': 'enroll',
 'thank': 'thanks',
 'sensitive': 'media',
 'average': 'mediocre',
 'facility': 'installation',
 'hood': 'cap',
 'hoodlum': 'tough',
 'bully': 'greatest',
 'bad': 'worse',
 'problematic': 'tough',
 'badly': 'poorly',
 'severely': 'seriously',
 'view': 'views',
 'perspective': 'views',
 'attitude': 'position',
 'status': 'position',
 'post': 'mailing',
 'office': 'role',
 'spot': 'points',
 'situation': 'position',
 'location': 'position',
 'side': 'english',
 'lay': 'position',
 'formally': 'officially',
 'inconceivable': 'impossible',
 'unacceptable': 'impossible',
 'weary': 'tire',
 'exhaust': 'beating',
 'cite': 'quotation',
 'acknowledgment': 'recognition',
 'credit': 'recognition',
 'reference': 'quotation',
 'mention': 'quotation',
 'quote': 'quotation',
 'smooth': 'smoothest',
 'fluid': 'mobile',
 'quiet': 'calm',
 'still': 'nonetheless',
 'toilet': 'throne',
 'lavatory': 'bathroom',
 'can': 'bums',
 'john': 'bathroom',
 'entire': 'intact',
 'problem': 'problems',
 'bother': 'troubling',
 'hassle': 'harass',
 'difficulty': 'trouble',
 'worry': 'cares',
 'disturb': 'troubling',
 'upset': 'troubling',
 'inconvenience': 'troubling',
 'ail': 'troubling',
 'pain': 'troubling',
 'par': 'equality',
 'comfort': 'consolation',
 'planning': 'preparation',
 'preparedness': 'preparation',
 'training': 'education',
 'closed': 'shut',
 'skill': 'acquisition',
 'ridiculousness': 'absurdity',
 'impact': 'touching',
 'touch': 'mite',
 'involve': 'needing',
 'sham': 'assumed',
 'impress': 'printed',
 'move': 'ran',
 'grant': 'awards',
 'appointment': 'engagement',
 'naming': 'assignment',
 'victim': 'dupe',
 'observation': 'reflection',
 'boil': 'churn',
 'bum': 'rats',
 'cheap': 'louder',
 'stock': 'trite',
 'fund': 'store',
 'memory': 'store',
 'storage': 'store',
 'depot': 'store',
 'commission': 'mission',
 'tone': 'feels',
 'feeling': 'feels',
 'flavor': 'feels',
 'look': 'appears',
 'smell': 'feels',
 'intent': 'captive',
 'life': 'lifetime',
 'heart': 'eyes',
 'shock': 'offended',
 'appal': 'offended',
 'outrage': 'offended',
 'alarm': 'appalling',
 'shocked': 'appalled',
 'return': 'passed',
 'inform': 'informed',
 'press': 'pressure',
 'agreement': 'understanding',
 'balance': 'balancing',
 'fella': 'cuss',
 'gent': 'cuss',
 'curse': 'cuss',
 'swear': 'rely',
 'passion': 'loves',
 'beloved': 'loves',
 'dear': 'loves',
 'honey': 'loves',
 'enjoy': 'loved',
 'know': 'loved',
 'screw': 'loved',
 'fuck': 'loved',
 'eff': 'loved',
 'bed': 'loved',
 'paper': 'newspaper',
 'dull': 'dulles',
 'slow': 'slowly',
 'windy': 'breezy',
 'closing': 'closure',
 'resolution': 'solution',
 'crossing': 'cross',
 'cover': 'screens',
 'scotch': 'crossed',
 'frustrate': 'crossed',
 'span': 'crossed',
 'sweep': 'crossed',
 'crabby': 'cross',
 'grouchy': 'cross',
 'grumpy': 'cross',
 'horrid': 'outrageous',
 'horrific': 'frightening',
 'steep': 'absorb',
 'unconscionable': 'outrageous',
 'usurious': 'outrageous',
 'lack': 'missing',
 'deficiency': 'want',
 'need': 'needing',
 'wish': 'cares',
 'desire': 'want',
 'require': 'needing',
 'world': 'existence',
 'man': 'mans',
 'manner': 'style',
 'way': 'means',
 'fashion': 'fashioned',
 'trend': 'drift',
 'title': 'entitle',
 'nozzle': 'nose',
 'scent': 'nose',
 'wind': 'rolling',
 'trade': 'trading',
 'offer': 'provides',
 'hat': 'hats',
 'package': 'box',
 'research': 'searching',
 'search': 'searching',
 'writer': 'author',
 'table': 'postpone',
 'card': 'lineup',
 'room': 'boarding',
 'promising': 'hopeful',
 'manifest': 'apparent',
 'show': 'registers',
 'foot': 'base',
 'bag': 'bags',
 'floor': 'dumps',
 'home': 'national',
 'theme': 'base',
 'infrastructure': 'base',
 'establish': 'launch',
 'found': 'launch',
 'mean': 'hateful',
 'reserve': 'reserved',
 'lick': 'working',
 'handicap': 'disabled',
 'auto': 'car',
 'automobile': 'car',
 'machine': 'car',
 'insult': 'insulting',
 'measure': 'bars',
 'total': 'numbered',
 'degree': 'points',
 'grade': 'ordering',
 'tier': 'level',
 'stage': 'leg',
 'story': 'history',
 'flat': 'mat',
 'plane': 'planes',
 'loser': 'losers',
 'bankruptcy': 'failure',
 'park': 'parking',
 'common': 'usual',
 'jet': 'green',
 'lot': 'deals',
 'mass': 'people',
 'mess': 'deals',
 'mint': 'deals',
 'mountain': 'deals',
 'pile': 'james',
 'plenty': 'deals',
 'raft': 'deals',
 'sight': 'views',
 'hand': 'passed',
 'treat': 'processing',
 'handle': 'cares',
 'consider': 'took',
 'contend': 'contest',
 'manage': 'cares',
 'sell': 'trading',
 'care': 'cares',
 'trust': 'rely',
 'disgraceful': 'black',
 'shameful': 'black',
 'interrupt': 'breaks',
 'instead': 'alternatively',
 'clog': 'congest',
 'surcharge': 'hooked',
 'overcharge': 'hooked',
 'excite': 'charging',
 'sex': 'exciting',
 'emotional': 'excited',
 'mad': 'insane',
 'mumble': 'gum',
 'prepare': 'organized',
 'ready': 'makes',
 'educate': 'school',
 'usable': 'operational',
 'useable': 'operational',
 'petty': 'little',
 'earth': 'globe',
 'ball': 'balls',
 'announcement': 'declaration',
 'dial': 'dialing',
 'pricey': 'pricy',
 'absolutely': 'utterly',
 'perfectly': 'utterly',
 'dead': 'suddenly',
 'gold': 'aus',
 'favor': 'privilege',
 'trial': 'run',
 'campaign': 'safari',
 'escape': 'flights',
 'extend': 'ran',
 'operate': 'working',
 'flow': 'hung',
 'feed': 'fed',
 'course': 'fed',
 'function': 'role',
 'range': 'rolling',
 'persist': 'ran',
 'bleed': 'ran',
 'hunt': 'ran',
 'race': 'ran',
 'melt': 'ran',
 'fake': 'pseudo',
 'fraud': 'pseudo',
 'bill': 'charging',
 'video': 'television',
 'tv': 'television',
 'blow': 'coke',
 'urge': 'cheers',
 'commend': 'recommend',
 'ice': 'iced',
 'send': 'charging',
 'pilot': 'flown',
 'menu': 'fares',
 'scare': 'scared',
 'dread': 'frightening',
 'horrendous': 'frightening',
 'assign': 'assigned',
 'portion': 'percentage',
 'specify': 'conditioning',
 'image': 'seeing',
 'repeat': 'reiterate',
 'replicate': 'copy',
 'twice': 'double',
 'pocket': 'bags',
 'sec': 'secs',
 's': 'secs',
 'moment': 'second',
 'mo': 'second',
 'minute': 'hours',
 'instant': 'wink',
 'back': 'backwards',
 'secondly': 'second',
 'conflict': 'engagement',
 'contradictory': 'conflicting',
 'dm': 'dms',
 'squeak': 'whine',
 'crave': 'starve',
 'golden': 'lucky',
 'surf': 'breaker',
 'dumb': 'speechless',
 'down': 'landed',
 'low': 'depression',
 'dark': 'night',
 'bear': 'assumed',
 'fend': 'stood',
 'substandard': 'inferior',
 'hour': 'hours',
 'hr': 'hours',
 'originate': 'initiate',
 'rise': 'hike',
 'lift': 'elevator',
 'awfully': 'terribly',
 'player': 'musician',
 'lip': 'rim',
 'mouth': 'speaking',
 'marriage': 'wedding',
 'tie': 'connected',
 'design': 'designs',
 'disappoint': 'disappointed',
 'freeze': 'freezing',
 'correct': 'decline',
 'right': 'proper',
 'tug': 'jerk',
 'ill': 'complaint',
 'potential': 'possible',
 'exchange': 'changing',
 'tot': 'add',
 'beverage': 'drink',
 'potable': 'drink',
 'swallow': 'drink',
 'booze': 'drink',
 'disaster': 'calamity',
 'last': 'lastly',
 'terminal': 'pole',
 'loud': 'loudly',
 'tacky': 'louder',
 'travel': 'moves',
 'activate': 'tripping',
 'light': 'lite',
 'scratch': 'cancelled',
 'ding': 'dent',
 'nick': 'notch',
 'survive': 'went',
 'live': 'hotter',
 'category': 'class',
 'family': 'kin',
 'form': 'working',
 'year': 'yrs',
 'sort': 'screens',
 'separate': 'disunite',
 'disorganize': 'disorganised',
 'disorganized': 'disorganised',
 'board': 'boarding',
 'warm': 'strong',
 'teen': 'teenager',
 'engage': 'took',
 'lost': 'preoccupied',
 'submit': 'took',
 'present': 'awards',
 'defer': 'postpone',
 'lose': 'misplaced',
 'drop': 'dropping',
 'lacking': 'missing',
 'conjunction': 'junction',
 'concentrate': 'focus',
 'centre': 'eyes',
 'rivet': 'focus',
 'final': 'finals',
 'news': 'intelligence',
 'word': 'phrase',
 'overhear': 'overheard',
 'important': 'crucial',
 'substantial': 'strong',
 'meaning': 'significant',
 'pregnant': 'significant',
 'origin': 'blood',
 'descent': 'blood',
 'dim': 'faint',
 'disastrous': 'black',
 'excuse': 'relieved',
 'apology': 'excuses',
 'explain': 'excuses',
 'apologize': 'excuses',
 'apologise': 'excuses',
 'justify': 'warrant',
 'aside': 'apart',
 'concern': 'cares',
 'forecast': 'estimated',
 'estimate': 'estimated',
 'figure': 'estimated',
 'luckily': 'fortunately',
 'rip': 'blood',
 'rent': 'took',
 'split': 'breaks',
 'hitch': 'jerk',
 'rub': 'wipe',
 'seats': 'seating',
 'sit': 'sat',
 'invest': 'clothing',
 'penny': 'cent',
 'fa': 'fas',
 'solid': 'strong',
 'firm': 'fastest',
 'livery': 'delivery',
 'rescue': 'delivery',
 'saving': 'economy',
 'ask': 'needing',
 'inquire': 'enquire',
 'investigate': 'enquire',
 'wonder': 'curiosity',
 'wholly': 'entirely',
 'completely': 'entirely',
 'totally': 'entirely',
 'exclusively': 'entirely',
 'freaky': 'bizarre',
 'satisfactory': 'acceptable',
 'distress': 'distressed',
 'unhappy': 'distressed',
 'stressed': 'distressed',
 'worried': 'distressed',
 'pop': 'kill',
 'soda': 'tonic',
 'brisk': 'alert',
 'fresh': 'unused',
 'refreshing': 'novel',
 'sick': 'disgusted',
 'cat': 'kats',
 'vague': 'faint',
 'trash': 'chalk',
 'free': 'relieved',
 'automate': 'automated',
 'talk': 'sing',
 'speak': 'speaking',
 'pact': 'accord',
 'agree': 'holding',
 'rag': 'scolding',
 'irritate': 'annoyed',
 'message': 'messaged',
 'capacity': 'capability',
 'count': 'numbered',
 'bet': 'wager',
 'nation': 'states',
 'land': 'states',
 'area': 'field',
 'nerve': 'cheek',
 'face': 'presenting',
 'gentleman': 'mans',
 'authoritative': 'classic',
 'definitive': 'classic',
 'rate': 'pace',
 'rank': 'absolute',
 'value': 'evaluate',
 'shit': 'rats',
 'excess': 'extra',
 'spare': 'extra',
 'additional': 'extra',
 'giant': 'giants',
 'acknowledge': 'receipt',
 'greet': 'greeting',
 'recover': 'regain',
 'reform': 'reclaim',
 'meeting': 'merging',
 'unite': 'connected',
 'merge': 'merged',
 'mix': 'merged',
 'combine': 'compound',
 'brood': 'hover',
 'dad': 'daddy',
 'remark': 'input',
 'comment': 'input',
 'target': 'points',
 'print': 'printed',
 'brand': 'blade',
 'stain': 'marks',
 'mug': 'marks',
 'scar': 'scared',
 'cross': 'crossed',
 'notice': 'marks',
 'note': 'marks',
 'pit': 'hell',
 'league': 'conference',
 'butt': 'bums',
 'ass': 'bums',
 'raise': 'kindle',
 'parent': 'rear',
 'outlet': 'issues',
 'leaving': 'departure',
 'difference': 'departure',
 'loss': 'red',
 'expiration': 'departure',
 'collection': 'accumulation',
 'crazy': 'unbalanced',
 'reasonably': 'pretty',
 'somewhat': 'slightly',
 'fairly': 'pretty',
 'assault': 'assaulted',
 'dishonor': 'shame',
 'peak': 'points',
 'summit': 'breast',
 'height': 'altitude',