<a href="https://colab.research.google.com/github/j019/Practical-Machine-Learning/blob/main/Day17/Recommendation_itemtrust.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install "numpy<2.0.0"

Collecting numpy<2.0.0
  Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 1.9 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 81.3 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

In [1]:
!pip install surprise

Collecting surprise
  Downloading surprise-0.1-py2.py3-none-any.whl.metadata (327 bytes)
Collecting scikit-surprise (from surprise)
  Downloading scikit_surprise-1.1.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (15 kB)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise->surprise) (1.5.3)
Requirement already satisfied: numpy>=1.24.1 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise->surprise) (1.26.4)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise->surprise) (1.16.3)
Downloading surprise-0.1-py2.py3-none-any.whl (1.8 kB)
Downloading scikit_surprise-1.1.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 24.1 MB/s eta 0:00:00
Installing collected packages: scikit-surprise, surprise
Successfully installed scikit-surprise-1.1.5 surprise-0.1

In [2]:
import surprise

In [3]:
import pandas as pd
import numpy as np
import surprise

In [4]:
ratings = pd.read_csv("/content/item_ratings.txt",sep=' ',names = ['uid','iid','rating'])
ratings.head()

   uid  iid  rating
0    1    1     2.0
1    1    2     4.0
2    1    3     3.5
3    1    4     3.0
4    1    5     4.0

In [5]:
lowest_rating = ratings['rating'].min()
highest_rating = ratings['rating'].max()

print("Ratings range between {0} and {1}".format(lowest_rating,highest_rating))

Ratings range between 0.5 and 4.0

In [6]:
reader = surprise.Reader(rating_scale = (lowest_rating,highest_rating))
data = surprise.Dataset.load_from_df(ratings,reader)

In [7]:
# AutoFolds --> We are keeping huge data in Folds
type(data)

surprise.dataset.DatasetAutoFolds

# Train the Algorithm for User Based Rating Prediction

In [98]:
similarity_options = {'name': 'cosine',
                      'user_based': True}
# Default k = 40
algo = surprise.KNNBasic(min_k=2,
                         sim_options = similarity_options,
                          verbose=5)
output = algo.fit(data.build_full_trainset())

Computing the cosine similarity matrix...
Done computing similarity matrix.

In [99]:
algo.__dict__.keys()

dict_keys(['bsl_options', 'sim_options', 'verbose', 'k', 'min_k', 'trainset', 'bu', 'bi', 'n_x', 'n_y', 'xr', 'yr', 'sim'])

In [100]:
algo.sim.shape

(1508, 1508)

In [101]:
ratings.nunique()

uid       1508
iid       2071
rating       8
dtype: int64

# Predict the rating of a Single Item by an User

In [102]:
pred = algo.predict(uid='708',iid='1507')
score = pred.est
print(score)

3.0028030537791928

### Verify from original Data

In [103]:
ratings.loc[(ratings['uid'] == 708) & (ratings['iid'] == 1507) , :]

       uid   iid  rating
17178  708  1507     1.5

In [104]:
pred = algo.predict(uid='50',iid='6')
score = pred.est
print(score)

3.0028030537791928

In [105]:
ratings.loc[(ratings['uid'] == 50) & (ratings['iid'] == 6) , :]

     uid  iid  rating
884   50    6     4.0

# Create Recommendations for an User id 707

## Predict Ratings of all Unrated Items by an User id 707

In [106]:
iids = ratings['iid'].unique()
iids50 = ratings.loc[ratings['uid'] == 707 ,'iid']
print("List of iid that uid={0} has rated:".format(707))
print(iids50)

List of iid that uid=707 has rated:
17170     10
17171    235
17172      2
17173    341
17174    207
17175      7
Name: iid, dtype: int64

In [107]:
iids_to_predict = np.setdiff1d(iids,iids50)
print("List of iid which uid={0} did not rate(in all {1}) :".format(707,len(iids_to_predict)))
print(iids_to_predict)
print("no of unrated items", len(iids_to_predict))

List of iid which uid=707 did not rate(in all 2065) :
[   1    3    4 ... 2069 2070 2071]
no of unrated items 2065

In [108]:
### ratings arbitrarily set to 0
testset = [[707,iid,0.] for iid in iids_to_predict]
predictions = algo.test(testset)
predictions[:-5]

[Prediction(uid=707, iid=1, r_ui=0.0, est=3.125, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=3, r_ui=0.0, est=3.0125, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=4, r_ui=0.0, est=3.424939968286814, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=5, r_ui=0.0, est=3.374996485072647, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=6, r_ui=0.0, est=3.087560862979787, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=8, r_ui=0.0, est=3.0000099088876437, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=9, r_ui=0.0, est=3.3500094216111687, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=11, r_ui=0.0, est=3.575, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=12, r_ui=0.0, est=2.687494494150231, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=13, r_ui=0.0, est=3.35, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=14, r_ui=0.0, est=0.9935147592935931, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=15, r_ui=0.0, est=2.2714985240743206, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=707, iid=16, r_ui=0.0, est=3.379316752151665, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=707, iid=17, r_ui=0.0, est=3.15, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=18, r_ui=0.0, est=3.5064852407064064, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=19, r_ui=0.0, est=3.0129704814128138, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=20, r_ui=0.0, est=2.496807352830392, details={'actual_k': 7, 'was_impossible': False}),
 Prediction(uid=707, iid=21, r_ui=0.0, est=2.6680901436532487, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=22, r_ui=0.0, est=2.7402721389403895, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=23, r_ui=0.0, est=3.5, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=24, r_ui=0.0, est=3.5308769562530644, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=707, iid=25, r_ui=0.0, est=2.242866202468351, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=26, r_ui=0.0, est=3.0349691482278423, details={'actual_k': 13, 'was_impossible': False}),
 Prediction(uid=707, iid=27, r_ui=0.0, est=3.2639642521214838, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=28, r_ui=0.0, est=2.5896761966638944, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=707, iid=29, r_ui=0.0, est=2.7762996161141804, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=707, iid=30, r_ui=0.0, est=3.227650856422255, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=707, iid=31, r_ui=0.0, est=2.740976493913542, details={'actual_k': 14, 'was_impossible': False}),
 Prediction(uid=707, iid=32, r_ui=0.0, est=1.7523779325105502, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=33, r_ui=0.0, est=3.25, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=34, r_ui=0.0, est=3.0000000000000004, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=35, r_ui=0.0, est=4.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=36, r_ui=0.0, est=1.2571337975316497, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=37, r_ui=0.0, est=2.9904882699578006, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=38, r_ui=0.0, est=3.0028030537791928, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=707, iid=39, r_ui=0.0, est=3.5064852407064064, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=40, r_ui=0.0, est=3.0095117300421994, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=41, r_ui=0.0, est=3.2597278610596105, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=42, r_ui=0.0, est=2.4849248831536954, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=43, r_ui=0.0, est=3.8824604029463017, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=707, iid=44, r_ui=0.0, est=3.753242620353203, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=45, r_ui=0.0, est=2.5, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=46, r_ui=0.0, est=1.4952441349789003, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=47, r_ui=0.0, est=1.976983774563634, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=48, r_ui=0.0, est=3.5064852407064064, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=49, r_ui=0.0, est=2.7532426203532037, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=50, r_ui=0.0, est=3.506976658973594, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=51, r_ui=0.0, est=2.793151362868114, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=707, iid=52, r_ui=0.0, est=3.761316557209145, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=707, iid=53, r_ui=0.0, est=3.7639320225002106, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=54, r_ui=0.0, est=4.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=55, r_ui=0.0, est=3.3272542485937375, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=56, r_ui=0.0, est=2.672212157345682, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=57, r_ui=0.0, est=2.128234869546997, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=58, r_ui=0.0, est=3.5064852407064064, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=59, r_ui=0.0, est=3.2464076096124446, details={'actual_k': 27, 'was_impossible': False}),
 Prediction(uid=707, iid=60, r_ui=0.0, est=3.5278640450004213, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=61, r_ui=0.0, est=2.233354472426151, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=62, r_ui=0.0, est=3.0129704814128138, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=63, r_ui=0.0, est=1.6737199657836157, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=64, r_ui=0.0, est=3.24371061030016, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=707, iid=65, r_ui=0.0, est=1.4904882699578008, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=66, r_ui=0.0, est=3.7639320225002106, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=67, r_ui=0.0, est=2.5142675950632993, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=68, r_ui=0.0, est=4.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=69, r_ui=0.0, est=3.415727719920648, details={'actual_k': 6, 'was_impossible': False}),
 Prediction(uid=707, iid=70, r_ui=0.0, est=2.4339931936341777, details={'actual_k': 13, 'was_impossible': False}),
 Prediction(uid=707, iid=71, r_ui=0.0, est=3.7639320225002106, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=72, r_ui=0.0, est=2.7476220674894507, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=73, r_ui=0.0, est=2.5873489151439335, details={'actual_k': 10, 'was_impossible': False}),
 Prediction(uid=707, iid=74, r_ui=0.0, est=3.25, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=75, r_ui=0.0, est=3.2639320225002106, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=76, r_ui=0.0, est=1.6803398874989486, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=77, r_ui=0.0, est=3.006485240706407, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=78, r_ui=0.0, est=3.0129704814128138, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=79, r_ui=0.0, est=3.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=80, r_ui=0.0, est=2.253242620353203, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=81, r_ui=0.0, est=3.1200894265732346, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=707, iid=82, r_ui=0.0, est=3.73606797749979, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=83, r_ui=0.0, est=2.495265902588414, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=707, iid=84, r_ui=0.0, est=3.0501973614362776, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=85, r_ui=0.0, est=3.3447620057725835, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=86, r_ui=0.0, est=3.5000000000000004, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=87, r_ui=0.0, est=3.253242620353203, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=88, r_ui=0.0, est=2.253242620353203, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=89, r_ui=0.0, est=1.9164078649987384, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=90, r_ui=0.0, est=3.07145895537544, details={'actual_k': 6, 'was_impossible': False}),
 Prediction(uid=707, iid=91, r_ui=0.0, est=3.2194850085136504, details={'actual_k': 21, 'was_impossible': False}),
 Prediction(uid=707, iid=92, r_ui=0.0, est=2.437190983173433, details={'actual_k': 7, 'was_impossible': False}),
 Prediction(uid=707, iid=93, r_ui=0.0, est=2.797658753069756, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=707, iid=94, r_ui=0.0, est=3.5064852407064064, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=95, r_ui=0.0, est=3.493514759293593, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=96, r_ui=0.0, est=3.829916264155701, details={'actual_k': 6, 'was_impossible': False}),
 Prediction(uid=707, iid=97, r_ui=0.0, est=4.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=98, r_ui=0.0, est=2.9952441349789005, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=99, r_ui=0.0, est=2.0129704814128138, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=100, r_ui=0.0, est=1.668526896782515, details={'actual_k': 6, 'was_impossible': False}),
 Prediction(uid=707, iid=101, r_ui=0.0, est=3.5, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=102, r_ui=0.0, est=3.752819153231685, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=707, iid=103, r_ui=0.0, est=3.4056018835604296, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=707, iid=104, r_ui=0.0, est=2.2482393492988484, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=105, r_ui=0.0, est=3.493514759293593, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=106, r_ui=0.0, est=2.506485240706407, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=107, r_ui=0.0, est=4.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=108, r_ui=0.0, est=1.7337868982339828, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=109, r_ui=0.0, est=3.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=110, r_ui=0.0, est=3.5064852407064064, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=111, r_ui=0.0, est=4.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=112, r_ui=0.0, est=2.9999999999999996, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=113, r_ui=0.0, est=0.7523779325105499, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=114, r_ui=0.0, est=3.5278640450004213, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=115, r_ui=0.0, est=3.3405081361250355, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=116, r_ui=0.0, est=1.4664268507553202, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=117, r_ui=0.0, est=3.7639320225002106, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=118, r_ui=0.0, est=4.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=119, r_ui=0.0, est=1.7523779325105502, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=120, r_ui=0.0, est=2.9952441349789005, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=121, r_ui=0.0, est=2.9749885758683767, details={'actual_k': 40, 'was_impossible': False}),
 Prediction(uid=707, iid=122, r_ui=0.0, est=2.2476220674894503, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=123, r_ui=0.0, est=3.0580066920480546, details={'actual_k': 8, 'was_impossible': False}),
 Prediction(uid=707, iid=124, r_ui=0.0, est=2.261889662552749, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=125, r_ui=0.0, est=1.5095117300421994, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=126, r_ui=0.0, est=3.881053159534161, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=707, iid=127, r_ui=0.0, est=2.310839684219094, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=128, r_ui=0.0, est=1.7381103374472509, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=129, r_ui=0.0, est=3.2597278610596105, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=130, r_ui=0.0, est=2.819402295310911, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=131, r_ui=0.0, est=2.981762745781211, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=132, r_ui=0.0, est=3.6755279943266026, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=133, r_ui=0.0, est=3.75, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=134, r_ui=0.0, est=3.3060436759954768, details={'actual_k': 8, 'was_impossible': False}),
 Prediction(uid=707, iid=135, r_ui=0.0, est=2.344561287196038, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=136, r_ui=0.0, est=4.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=137, r_ui=0.0, est=1.74027213894039, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=138, r_ui=0.0, est=2.75, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=139, r_ui=0.0, est=3.23606797749979, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=140, r_ui=0.0, est=3.25, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=141, r_ui=0.0, est=3.17241433801949, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=142, r_ui=0.0, est=4.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=143, r_ui=0.0, est=3.0915501149408975, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=707, iid=144, r_ui=0.0, est=3.831916989916784, details={'actual_k': 6, 'was_impossible': False}),
 Prediction(uid=707, iid=145, r_ui=0.0, est=3.5064852407064064, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=146, r_ui=0.0, est=2.3386009264931857, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=147, r_ui=0.0, est=3.7639320225002106, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=148, r_ui=0.0, est=3.0571639740225667, details={'actual_k': 19, 'was_impossible': False}),
 Prediction(uid=707, iid=149, r_ui=0.0, est=2.5095117300422, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=150, r_ui=0.0, est=3.316322517448075, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=151, r_ui=0.0, est=3.5278640450004213, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=152, r_ui=0.0, est=3.5000000000000004, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=153, r_ui=0.0, est=2.9442719099991588, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=154, r_ui=0.0, est=2.242866202468351, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=155, r_ui=0.0, est=3.5278640450004213, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=156, r_ui=0.0, est=1.0047558650210997, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=157, r_ui=0.0, est=2.6190339035825367, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=707, iid=158, r_ui=0.0, est=2.5142675950632993, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=159, r_ui=0.0, est=2.8059708549080655, details={'actual_k': 8, 'was_impossible': False}),
 Prediction(uid=707, iid=160, r_ui=0.0, est=3.089584317915349, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=707, iid=161, r_ui=0.0, est=3.5278640450004213, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=162, r_ui=0.0, est=4.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=163, r_ui=0.0, est=2.6825043942876117, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=164, r_ui=0.0, est=3.75, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=165, r_ui=0.0, est=3.2467573796467963, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=166, r_ui=0.0, est=2.2726983424724243, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=167, r_ui=0.0, est=3.5798943325494488, details={'actual_k': 7, 'was_impossible': False}),
 Prediction(uid=707, iid=168, r_ui=0.0, est=3.5064852407064064, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=169, r_ui=0.0, est=2.245875137173679, details={'actual_k': 8, 'was_impossible': False}),
 Prediction(uid=707, iid=170, r_ui=0.0, est=2.318522822828883, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=171, r_ui=0.0, est=1.4952441349789003, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=172, r_ui=0.0, est=3.12556611778644, details={'actual_k': 7, 'was_impossible': False}),
 Prediction(uid=707, iid=173, r_ui=0.0, est=2.0, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=174, r_ui=0.0, est=3.5017477237840984, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=175, r_ui=0.0, est=0.7532426203532034, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=176, r_ui=0.0, est=2.75972786105961, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=177, r_ui=0.0, est=2.5, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=178, r_ui=0.0, est=3.8353281766136686, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=179, r_ui=0.0, est=1.5095117300421994, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=707, iid=180, r_ui=0.0, est=3.331909856346751, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=707, iid=181, r_ui=0.0, est=3.573441692385817, details={'actual_k': 6, 'was_impossible': False}),

In [109]:
pred_ratings = np.array([pred.est for pred in predictions])
pred_ratings[:5]

array([3.125     , 3.0125    , 3.42493997, 3.37499649, 3.08756086])

In [110]:
pred_ratings.shape

(2065,)

In [111]:
# Finding the index of maximum predicted rating
i_max = pred_ratings.argmax()

In [112]:
# Recommending the item with maximum predicted rating
iid_recommend_most = iids_to_predict[i_max]
print("Top item to be recommended for user {0} is {1} with predicted rating as {2}".format(707,iid_recommend_most,pred_ratings[i_max]))

Top item to be recommended for user 707 is 35 with predicted rating as 4.0

In [113]:
# Getting top 10 items to be recommended for uid = 707
import heapq # use priority queue algorithm.
i_sorted_10 = heapq.nlargest(10, range(len(pred_ratings)), pred_ratings.take)
top_10_items = iids_to_predict[i_sorted_10]
print(top_10_items)

[ 35  54  68  97 107 111 118 136 142 162]

In [97]:
# for uid = 707 'msd similarity'
# [ 35  54  68  97 107 111 118 136 142 162]

In [80]:
# for uid = 707 'cosine similarity'
#[ 23  33  74  79 101 109 111 133 138 140] --> Item Based
#[ 11  35  54  68  97 107 111 118 136 142] --> User Based

In [ ]:
# Task Uid = 700 / 707 / 708

# Check performance of Recommendation system

# Train test split

In [114]:
from surprise.model_selection import train_test_split

In [115]:
X_train, X_test = train_test_split(data,
                                   test_size=0.3,
                                   random_state=7)

In [116]:
X_train

In [258]:
similarity_options = {'name': 'pearson_baseline',
                      'user_based': False}
# Default k = 40
# k = 5, 40, 100
# min_k = 2, 5
algo = surprise.KNNBasic(min_k = 2,k = 40,sim_options = similarity_options,
                         verbose=5)
output = algo.fit(X_train)

Estimating biases using als...
Computing the pearson_baseline similarity matrix...
Done computing similarity matrix.

In [259]:
predictions = algo.test(X_test)

In [260]:
from surprise.accuracy import mae , mse

In [261]:
mae(predictions)

MAE:  0.6266

0.6265790984511914

In [262]:
mse(predictions)

MSE: 0.6858

0.6857738912645619

In [263]:
len(X_test)

10650

# Check Count of Impossible Predictions

In [264]:
count = 0
for p in predictions:
  if p.details['was_impossible']:
    count += 1
print(count)

1415

In [265]:
predictions[10000:10050]

[Prediction(uid=105, iid=254, r_ui=2.5, est=3.005413128345474, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=1101, iid=214, r_ui=2.5, est=3.0518257614496886, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=891, iid=2, r_ui=2.5, est=2.404590589474929, details={'actual_k': 10, 'was_impossible': False}),
 Prediction(uid=825, iid=728, r_ui=4.0, est=3.8290511236415297, details={'actual_k': 8, 'was_impossible': False}),
 Prediction(uid=3, iid=148, r_ui=3.5, est=2.844399153447355, details={'actual_k': 4, 'was_impossible': False}),
 Prediction(uid=1417, iid=419, r_ui=4.0, est=3.3797076634455303, details={'actual_k': 6, 'was_impossible': False}),
 Prediction(uid=1355, iid=593, r_ui=4.0, est=2.5278132220526386, details={'actual_k': 6, 'was_impossible': False}),
 Prediction(uid=209, iid=245, r_ui=3.0, est=2.924874330327155, details={'actual_k': 20, 'was_impossible': False}),
 Prediction(uid=72, iid=235, r_ui=3.0, est=3.4084853872440277, details={'actual_k': 16, 'was_impossible': False}),
 Prediction(uid=445, iid=213, r_ui=1.5, est=2.2627517793687124, details={'actual_k': 20, 'was_impossible': False}),
 Prediction(uid=570, iid=250, r_ui=3.5, est=3.27488023627064, details={'actual_k': 16, 'was_impossible': False}),
 Prediction(uid=760, iid=13, r_ui=3.5, est=2.892465798820728, details={'actual_k': 21, 'was_impossible': False}),
 Prediction(uid=188, iid=520, r_ui=4.0, est=2.835520651517229, details={'actual_k': 18, 'was_impossible': False}),
 Prediction(uid=842, iid=247, r_ui=3.5, est=3.004433263319181, details={'actual_k': 31, 'was_impossible': False}),
 Prediction(uid=805, iid=8, r_ui=4.0, est=3.672134048706434, details={'actual_k': 3, 'was_impossible': False}),
 Prediction(uid=519, iid=219, r_ui=4.0, est=3.3540425467601778, details={'actual_k': 7, 'was_impossible': False}),
 Prediction(uid=206, iid=215, r_ui=4.0, est=3.6731356870062473, details={'actual_k': 18, 'was_impossible': False}),
 Prediction(uid=114, iid=235, r_ui=4.0, est=2.534392523815248, details={'actual_k': 14, 'was_impossible': False}),
 Prediction(uid=328, iid=17, r_ui=2.5, est=2.4387071858204976, details={'actual_k': 18, 'was_impossible': False}),
 Prediction(uid=907, iid=215, r_ui=3.0, est=2.5254668712416244, details={'actual_k': 15, 'was_impossible': False}),
 Prediction(uid=1089, iid=245, r_ui=0.5, est=2.2041465801683335, details={'actual_k': 22, 'was_impossible': False}),
 Prediction(uid=209, iid=206, r_ui=2.5, est=2.651400072050547, details={'actual_k': 17, 'was_impossible': False}),
 Prediction(uid=487, iid=6, r_ui=2.0, est=2.9547771147454354, details={'actual_k': 27, 'was_impossible': False}),
 Prediction(uid=1067, iid=239, r_ui=3.0, est=3.2049345398353863, details={'actual_k': 7, 'was_impossible': False}),
 Prediction(uid=728, iid=257, r_ui=1.0, est=3.841707499934456, details={'actual_k': 2, 'was_impossible': False}),
 Prediction(uid=494, iid=17, r_ui=3.0, est=3.3873902797092006, details={'actual_k': 14, 'was_impossible': False}),
 Prediction(uid=936, iid=250, r_ui=2.5, est=3.0656676587106553, details={'actual_k': 8, 'was_impossible': False}),
 Prediction(uid=460, iid=243, r_ui=1.5, est=2.9045370846084273, details={'actual_k': 18, 'was_impossible': False}),
 Prediction(uid=161, iid=658, r_ui=3.5, est=2.951682929850528, details={'actual_k': 33, 'was_impossible': False}),
 Prediction(uid=235, iid=239, r_ui=4.0, est=3.1335705039400907, details={'actual_k': 21, 'was_impossible': False}),
 Prediction(uid=442, iid=235, r_ui=3.0, est=3.0249417634125093, details={'actual_k': 21, 'was_impossible': False}),
 Prediction(uid=1286, iid=257, r_ui=2.5, est=3.08869884711039, details={'actual_k': 14, 'was_impossible': False}),
 Prediction(uid=396, iid=235, r_ui=1.5, est=3.1333797702591526, details={'actual_k': 10, 'was_impossible': False}),
 Prediction(uid=800, iid=213, r_ui=3.5, est=2.839369688079507, details={'actual_k': 23, 'was_impossible': False}),
 Prediction(uid=1062, iid=9, r_ui=4.0, est=3.5195626804427453, details={'actual_k': 9, 'was_impossible': False}),
 Prediction(uid=1104, iid=610, r_ui=3.5, est=3.005413128345474, details={'was_impossible': True, 'reason': 'Not enough neighbors.'}),
 Prediction(uid=608, iid=220, r_ui=2.5, est=3.4085834956105914, details={'actual_k': 7, 'was_impossible': False}),
 Prediction(uid=188, iid=211, r_ui=4.0, est=2.822957735664794, details={'actual_k': 20, 'was_impossible': False}),
 Prediction(uid=542, iid=11, r_ui=4.0, est=3.6131834002483854, details={'actual_k': 5, 'was_impossible': False}),
 Prediction(uid=1193, iid=4, r_ui=3.5, est=3.2010860938921457, details={'actual_k': 24, 'was_impossible': False}),
 Prediction(uid=161, iid=675, r_ui=2.5, est=3.258955213575443, details={'actual_k': 28, 'was_impossible': False}),
 Prediction(uid=1152, iid=244, r_ui=3.5, est=3.4265737326156698, details={'actual_k': 27, 'was_impossible': False}),
 Prediction(uid=507, iid=6, r_ui=4.0, est=3.4469481714871657, details={'actual_k': 25, 'was_impossible': False}),
 Prediction(uid=46, iid=4, r_ui=3.0, est=3.3192267130863033, details={'actual_k': 8, 'was_impossible': False}),
 Prediction(uid=1461, iid=206, r_ui=2.5, est=2.6644129690313636, details={'actual_k': 16, 'was_impossible': False}),
 Prediction(uid=1476, iid=243, r_ui=4.0, est=3.8340131730482283, details={'actual_k': 23, 'was_impossible': False}),
 Prediction(uid=1073, iid=245, r_ui=3.5, est=3.6765963722429222, details={'actual_k': 22, 'was_impossible': False}),
 Prediction(uid=747, iid=256, r_ui=3.0, est=3.0821300172273385, details={'actual_k': 27, 'was_impossible': False}),
 Prediction(uid=971, iid=255, r_ui=2.5, est=2.8892191693002798, details={'actual_k': 20, 'was_impossible': False}),
 Prediction(uid=1335, iid=241, r_ui=3.0, est=2.898880427124799, details={'actual_k': 18, 'was_impossible': False})]